version: 1
formatters:
  default:
    format: '%(asctime)s [%(levelname)s] serpbot %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : INFO
root:
  level: INFO
  handlers: [console]